# Generated by Django 4.2.16 on 2024-12-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='completed_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
