# Generated by Django 4.2.5 on 2024-12-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizhistory_completed_date_quizhistory_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='options',
            field=models.JSONField(),
        ),
    ]
