# Generated by Django 4.2.5 on 2024-12-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='options',
            field=models.JSONField(default=1, null=True),
        ),
    ]
