# Generated by Django 4.2.5 on 2024-12-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='options',
            field=models.JSONField(null=True),
        ),
    ]
